#! /bin/bash

nstep=100000

for n in 16 24 32 48 64 80 96 128; do

    folder=BA_$n

    echo BA resolution: $n folder $folder

    python3 meeuuw.py --e 25 --nelx $n --nelz $n --nstep $nstep --formulation 'BA' --output_folder $folder > opla_BA_$n &

    ###############################################

    folder=EBA_$n

    echo EBA resolution: $n folder $folder

    python3 meeuuw.py --e 25 --nelx $n --nelz $n --nstep $nstep --formulation 'EBA' --output_folder $folder > opla_EBA_$n &


done

