#! /bin/bash

rm errors.ascii
rm solve_times.ascii

for n in 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 36 41 43 48 57 64 80 89 96 105 112 128 144 160; do

    echo resolution: $n

    python3 meeuuw.py --e 19 --nelx $n --nelz $n  > opla
    grep errv opla >> errors.ascii
    grep solve opla  | grep Stokes >> solve_times.ascii

done
