#! /bin/bash

for e in 0 1 2 3 4 5 6 7 8 9 10; do

    echo ---------------------------------- 
    echo  experiment $e

    python3 meeuuw.py $e 4 5 1 > opla
    grep vrms opla 
    mv opla opla_${e}

done


