#! /bin/bash

e=15
nstep=1
axi=1

for n  in 16 32 48 64 80 96 128 160 192; do
    #echo resolution: $n
    python3 meeuuw.py $e $n $n $nstep $axi 0 0 | grep sample >> measurements_exp15.ascii
    mv OUTPUT/profile_horizontal.ascii OUTPUT/profile_horizontal_${n}.ascii

done
