#! /bin/bash


for n in 16 24 32 48 64 ; do

    echo resolution: $n

    python3 meeuuw.py --e 0 --nelx $n --nelz $n --nstep 400  > opla_${n}.txt
    mkdir OUTPUT_${n}
    mv OUTPUT/vrms* OUTPUT_${n}/ 
    mv OUTPUT/Nu* OUTPUT_${n}/ 
    mv OUTPUT/profile_vertical.ascii OUTPUT_${n}/ 

done
