#! /bin/bash

#   nelx  = int(sys.argv[2])
#   nelz  = int(sys.argv[3])
#   nstep = int(sys.argv[4])
#   axisymmetric=(int(sys.argv[5])==1)
#   remove_rho_profile=(int(sys.argv[6])==1)
#   straighten_edges=(int(sys.argv[7])==1)

e=13
nstep=1

for n  in 16 24 32 48 64 80 96 128; do
    #echo resolution: $n
    python3 meeuuw.py $e $n $n $nstep 0 1 0 | grep sample >> measurements_exp13.ascii
    mv OUTPUT/profile_vertical.ascii OUTPUT/profile_vertical_${n}.ascii

done
